package com.example.Backend.common.enums;

public enum Status {
    WAITING_FOR_INTERVIEW,
    WAITING_FOR_APPROVAL,
    WAITING_FOR_RESPONSE,
    OPEN,
    PASSED_INTERVIEW,
    APPROVED_OFFER,
    REJECTED_OFFER,
    ACCEPTED_OFFER,
    DECLINED_OFFER,
    CANCELLED_OFFER,
    FAILED_INTERVIEW,
    CANCELED_INTERVIEW,
    BANNED
}
